<script src="{{ url('Frontend') }}/js/vendor/jquery-2.2.4.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="{{ url('Frontend') }}/js/vendor/bootstrap.min.js"></script>
<script src="{{ url('Frontend') }}/https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
<script src="{{ url('Frontend') }}/js/easing.min.js"></script>
<script src="{{ url('Frontend') }}/js/hoverIntent.js"></script>
<script src="{{ url('Frontend') }}/js/superfish.min.js"></script>
<script src="{{ url('Frontend') }}/js/jquery.ajaxchimp.min.js"></script>
<script src="{{ url('Frontend') }}/js/jquery.magnific-popup.min.js"></script>
<script src="{{ url('Frontend') }}/js/mn-accordion.js"></script>
<script src="{{ url('Frontend') }}/js/jquery-ui.js"></script>
<script src="{{ url('Frontend') }}/js/jquery.nice-select.min.js"></script>
<script src="{{ url('Frontend') }}/js/owl.carousel.min.js"></script>
<script src="{{ url('Frontend') }}/js/mail-script.js"></script>
<script src="{{ url('Frontend') }}/js/main.js"></script>